### PR TITLE
PR: Update script cleanocpu.sh to long paths.

### PR DESCRIPTION
**Pull request by stefvanbuuren**
I run `opencpu-server` on Ubuntu 18.04 and experienced that the script `/usr/lib/opencpu/scripts/cleanocpu.sh` did not work on my system.  As a consequence, the directory `tmp/ocpu-store` kept on growing. My "solution" thus far was to reboot the server every night, so in the morning opencpu could start fresh. Due to increased traffic this is no longer feasible. A similar report is at <https://groups.google.com/g/opencpu/c/1xYywG7Zc6U/m/GFdhoNreAAAJ>.

This PR implements a few changes to the `cleanocpu.sh` script that deletes old files when the temporary files are in long paths, e.g. `/tmp/systemd-private-7b2421...525414ed882-apache2.service-4gzzHl`. 

Since the script only functions when run as `root`, I also applied a change in the cron invocation command.

Note: I have tested this only on Ubuntu 18.04.

### CODE REVIEW

**Comment by jeroen** [comment]
Thank you for raising the issue.

The underlying issue here is that the location of the apache's /tmp depends on if apache2 is running as a systemd service with the `PrivateTmp` flag. This seems to be the default in a regular installation on ubuntu 18.04+. But when running on docker (which does not use systemd) this is not the case, and the tempdir is just `/tmp`.

I think that for the systemd scenario there is a more elegant solution that doesn't require the ugly cron script, and instead create a config file that takes advantage of the systemd `tmpfiles.d` cleanup service:

 - https://www.freedesktop.org/software/systemd/man/systemd-tmpfiles-setup.service.html
 - https://www.freedesktop.org/software/systemd/man/tmpfiles.d.html

If I read this correctly we should be able to define a config like this in `/usr/lib/tmpfiles.d/ocpu.conf`

```
e     /tmp/systemd-private*apache*/tmp/ocpu-temp/*   0755 www-data www-data  1h -
e     /tmp/systemd-private*apache*/tmp/ocpu-store/*  0755 www-data www-data  1d -
```

Reload the config:

```sh
systemctl restart systemd-tmpfiles-clean.service
```

And then we can test it using:

```
systemd-tmpfiles --clean
```

Some old files seem gone. So if that works, we could make this part of the default opencpu installation. But I need to test how often systemd will actually run the cleanup job in practice, and if this really doesn't clean too aggressively.

**Comment by jeroen** [comment]
According to [this topic](https://unix.stackexchange.com/questions/452811/how-to-edit-the-timer-for-systemd-tmpfiles-clean) the systemd cleanup timer actually one runs once per day by default. See:

```
 systemctl cat systemd-tmpfiles-clean.timer
```

But maybe that suffices.

**Comment by jeroen** [comment]
I added a slightly different solution that should find the correct tmp, regardless of how apache was started.

**Comment by jeroen** [comment]
Lmk if this seems to work when you get a change to `apt-get upgrade` your server.

**Comment by stefvanbuuren** [comment]
Thanks a million for diving in.

I wasn't aware of the difference between the Ubuntu 18.04 versions for server and docker. Your solution is much more elegant than what I was able to do.

Just installed your update on the server, reset cleaning times to 30 and 60 minutes respectively. Will keep an eye on disk use during the day to see whether the patch works.

**Comment by stefvanbuuren** [comment]
Yes, it works great on both my server and docker versions of Ubuntu. I changed back the cron user from `root` to `www-data`, and it kept working. 

Thanks for solving this.

**Pull request closed without merging**
